apiVersion: operator.dataverse.redhat.com/v1alpha1
kind: Group
metadata:
  labels:
    app.kubernetes.io/name: usernaut
    app.kubernetes.io/managed-by: kustomize
  name: dataverse-aggregate-mygroup
  namespace: usernaut
spec:
  group_name: dataverse-aggregate-mygroup
  members:
   users:
    - subhatta
    - rmandal
  group_params:
    - backend: gitlab
      name: gitlab
      property: project_access_paths
      value:
        - dataverse/datavers-config/dataproduct-config
        - dataverse/astro/astro-toolkit
        - dataverse/platform-tooling/fivetran_terraform
  backends:
  - name: fivetran
    type: fivetran
  - name: rhplatformtest
    type: "snowflake"
